-- Generated by HyprMod

-- Environment
hl.env("XCURSOR_THEME", "miku-cursor-linux")
hl.env("XCURSOR_SIZE", "24")

-- Settings
hl.config({
    cursor = {
        hide_on_key_press = true,
    },
    decoration = {
        blur = {
            enabled = true,
            passes = 2,
            size = 3,
            vibrancy_darkness = 0.0,
            xray = false,
        },
        dim_around = 0.4,
        dim_inactive = false,
        dim_strength = 0.5,
        inactive_opacity = 0.8,
        rounding = 7,
        shadow = {
            enabled = true,
            range = 4,
            render_power = 2,
        },
    },
    dwindle = {
        smart_split = false,
    },
    general = {
        col = {
            active_border = {
                colors = {"rgba(3d3846ff)"},
                angle = 45,
            },
            inactive_border = "0xaa595959",
        },
        layout = "dwindle",
    },
    input = {
        numlock_by_default = true,
        sensitivity = 0.15,
    },
    misc = {
        disable_hyprland_logo = true,
        disable_splash_rendering = true,
    },
})

-- Bezier curves
hl.curve("easeOutQuint", { type = "bezier", points = { {0.23, 1.0}, {0.32, 1.0} } })

-- Animations
hl.animation({
    leaf = "workspaces",
    enabled = true,
    speed = 4.0,
    bezier = "easeOutQuint",
    style = "slide",
})
hl.animation({
    leaf = "workspacesIn",
    enabled = true,
    speed = 4.0,
    bezier = "easeOutQuint",
    style = "slide",
})
hl.animation({
    leaf = "workspacesOut",
    enabled = true,
    speed = 4.0,
    bezier = "easeOutQuint",
    style = "slide",
})

-- Monitors
hl.monitor({
    output = "VGA-1",
    disabled = false,
    mode = "1366x768@59.79Hz",
    position = "0x0",
    scale = 1,
    cm = "srgb",
})

-- Workspaces
hl.workspace_rule({
    workspace = "r[1-6]",
    default = true,
    persistent = true,
})

-- Keybinds
hl.unbind("SUPER + M")
hl.bind("SUPER + M", hl.dsp.exec_cmd("~/.config/rofi/scripts/powermenu.sh"))
hl.unbind("SUPER + N")
hl.bind("SUPER + N", hl.dsp.exec_cmd("swaync-client -t -sw"))
hl.unbind("SUPER + R")
hl.bind("SUPER + R", hl.dsp.exec_cmd("~/.config/rofi/scripts/launcher.sh"))
hl.unbind("SHIFT + Print")
hl.bind("SHIFT + Print", hl.dsp.exec_cmd("~/.config/rofi/scripts/screenshot.sh"))
hl.unbind("F11")
hl.bind("F11", hl.dsp.window.fullscreen())
hl.unbind("SUPER + W")
hl.bind("SUPER + W", hl.dsp.exec_cmd("~/.config/rofi/scripts/wallpaper.sh"))
hl.unbind("Pause")
hl.bind("Pause", hl.dsp.exec_cmd("playerctl play-pause"))
hl.unbind("Print")
hl.bind("Print", hl.dsp.exec_cmd("~/.config/rofi/scripts/screenshot.sh --fullscreen"))
hl.unbind("XF86Sleep")
hl.bind("XF86Sleep", hl.dsp.exec_cmd("python3 ~/Projects/Sandrone/start.py"))

-- Window rules
hl.window_rule({
    name = "Bluetooth",
    match = {
        class = "^(blueman-manager|org\\.kde\\.kdeconnect\\.app|org.pulseaudio.pavucontrol)$",
    },
    float = true,
})

-- Layer rules
hl.layer_rule({
    match = {
        namespace = "rofi",
    },
    dim_around = true,
})
hl.layer_rule({
    match = {
        namespace = "swaync-control-center",
    },
    animation = "slide right",
})

-- Autostart
hl.on("hyprland.start", function()
    hl.exec_cmd("noctalia")
    hl.exec_cmd("valent --gapplication-service")
end)
